sudo: required
dist: trusty
language: c
compiler:
        - clang
matrix:
  allow_failures:
    - compiler: clang
addons:
  apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - realpath
        - libpango1.0-dev
        - libpcre3-dev
        - texlive-latex-recommended
        - texlive-fonts-extra
        - texinfo
        - gcc-4.9
        - gfortran
        - zlib1g-dev
        - libbz2-dev
        - liblzma-dev
        - libpcre3-dev
        - libedit-dev

script:
        - cd R
        - ./configure --enable-R-shlib --with-included-gettext --enable-R-profiling --enable-memory-profiling
        - svn info
        - travis_wait 60 make
        - travis_wait 60 make check
