sudo: required
dist: trusty
language: c
compiler:
        - clang
matrix:
  allow_failures:
    - compiler: gcc
addons:
  apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - gfortran
        - zlib1g-dev
        - libbz2-dev
        - liblzma-dev
        - libpcre3-dev
        - libedit-dev

script:
        - ./configure --enable-R-shlib --with-included-gettext --enable-R-profiling --enable-memory-profiling
        - travis_wait 60 make -j 2
        - travis_wait 60 make -j 2 check
